# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b076966419f8a0982b09047a3080f58c25d571790b58c70fd2ba5be363586dd7985de5715bf56a0f5ef7cf9409ddc856afc54dd5fa76277e93be38c87bb312

test:
  secret_key_base: 21f60487914136fe7f411576b8a7c452d0d4b1734e5cfb4fcc4a72c6ced17934840f7d2836baae8c6118613a227181152f932f1b6a651284a0a7f547b3325ebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
